### ISSUE TITLE
Adjust collection for election news in other jurisdictions?

### ISSUE THREAD

**Issue by Stwissel** [IBM-Bluemix/election-insights#1]
Pretty cool app. I was wondering how can I adjust it to use sources for other upcoming elections (like in my country of residence, Singapore). We have different news sources and the political functions and politicians are different

**Comment by kauffecup** [comment]
Unfortunately, I'm not sure how easy it will be to use different news sources. I'm using http://www.alchemyapi.com/products/alchemydata-news which handles the parsing of news articles as they come in, meaning I only need to query their database. They claim to have 75,000+ sources so there might be a way to exclude more US-centric sources with a more complicated query.

Right now the query that I'm using is:

```
q.enriched.url.enrichedTitle.taxonomy.taxonomy_': '|label=elections,score=>0.75|
```

You can play with different test queries here and see what kind of responses you'll get: http://querybuilder.alchemyapi.com/builder

Alternatively (but more difficultly), you could set up a process where you manually feed the articles you want in to AlchemyLanguage (http://www.alchemyapi.com/products/alchemylanguage) which will give you the data in the same format that AlchemyNews will. This is what AlchemyNews does... it's just easier to use AlchemyNews because they already do it for you :smile:
