### ISSUE TITLE
Election insights shows concepts other than election candidates or election news

### ISSUE THREAD

**Issue by salilahuja** [IBM-Bluemix/election-insights#2]
We need to either change app title to news insights or restrict the news feed to election or election candidate related news. Right now the circles have entities from around the world

**Comment by kauffecup** [comment]
The current alchemy query we're using is:

``` sh
q.enriched.url.enrichedTitle.taxonomy.taxonomy_': '|label=elections,score=>0.75|
```

It's not specific to the U.S. in any way - just all news articles that Alchemy is more than 75% confident are about elections

Given this, I'm not sure what else to name it :smile: - maybe "World Election Insights" ...? so that it's more clear? What do you think?

For a more detailed breakdown on what alchemynews can give, click [here](http://www.alchemyapi.com/api/taxonomy)
