### ISSUE TITLE
website crashed

### ISSUE THREAD

**Issue by luciencd** [IBM-Bluemix/election-insights#4]
http://electioninsights.mybluemix.net/#/
The website crashed when I accidentally/somehow moved the left handle to the right of the right handle (this was on the dates handle).
I think when the handles switched, it may have triggered a divide by zero error.

Anyways, the website is down, whoops.

**Comment by kauffecup** [comment]
Fixed via https://github.com/IBM-Bluemix/election-insights/commit/37f9cea7710a784b1d95b118e1cdb6d3947b288f

The issue was we were printing `response.result.docs.length` - if no docs were returned (no new articles in the last X minutes), the "docs" object is empty. To remedy this, we make sure that object is there before referencing it
